### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by Bairdo**

### CODE REVIEW

**Comment by Bairdo** [comment]
I'm using PyCharm, with the docker plugin to run these remotely. Connecting from a dev machine (Arch) to a remote Ubuntu server. This does require docker-compose on the dev machine.

**Comment by samrussell** [comment]
This looks tidy, am reproducing this locally now

**Comment by samrussell** [comment]
This is a definite step in the right direction, thanks for your work on this!

A couple requests:

- Can we do this with schema version 2? Faucet is holding back on that for a couple reasons so I'm keen to stay consistent with that
- Can we keep the images static and just mount the source/config as volumes? These images aren't part of the automated test suite so they're not intended to run on travis; rather they're as a debugging and sanity checking tool as the unit test suite should be good enough to cover everything

Feel free to delete the hostapd stuff, I had started out using that but it's not been touched and doesn't need to turn up in the docker-compose setup.

**Comment by Bairdo** [comment]
Ok updated. I've left the requirements.txt as a copy - don't see the point in duplicating the location of packages to be installed.

The project directory will need to be copied (rsync) over to the remote machine or the volumes will not work

**Comment by Bairdo** [comment]
done

**Comment by samrussell** [comment]
The wpasupplicant image is looking good but the test one is failing - can we do the pip install at image creation time instead? The containers don't have internet access (by design) so we can't pip-install inside of them

**Comment by Bairdo** [comment]
Ive reverted that last commit, I think it is the cleaner way to install the dependencies without having multiple lists.

When you say the containers don't have internet access by design, do you mean at deployment (real network) time

**Comment by samrussell** [comment]
What do you mean by "real network"? The containers are for sanity checking, so they're not meant to be used in the wild.

Also I'm still not able to get the test container to start - have you got it working at your end?

**Comment by Bairdo** [comment]
i believe so 
```
docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS              PORTS               NAMES
18491a8f3acf        chewie/chewie:latest          "bash -c 'python3 /c…"   About a minute ago   Up About a minute                       chewie_test_1
ce379e8e4921        chewie/wpasupplicant:latest   "bash -c 'wpa_suppli…"   About a minute ago   Up About a minute                       chewie_wpasupplicant_1
```

and the process is running. although im not getting any log output from the pycharm docker plugin.
```
ps ax
  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:00 python3 /chewie-src/run.py
    7 pts/0    Ss     0:00 bash
   20 pts/0    R+     0:00 ps ax
```

and the wpasupplicant is successfully authenticating.
```
EAPOL: SUPP_PAE entering state AUTHENTICATED
EAPOL: Supplicant port status: Authorized
EAPOL: SUPP_BE entering state RECEIVE
EAPOL: SUPP_BE entering state SUCCESS
EAPOL: SUPP_BE entering state IDLE
EAPOL authentication completed - result=SUCCESS
```

**Comment by Bairdo** [comment]
real network as in if someone like brad (a user) were to use them in production (ie. not a developer).
Then why can it not have an internet connection if it's just for development?

**Comment by Bairdo** [comment]
Re not starting: have you copied over the project root directory to the remote server?

**Comment by samrussell** [comment]
Turns out docker is hardcoded to use 8.8.8.8 and I have that blackholed on my home network.

The -it flag hadn't been replicated in the docker-compose.yaml so I've added that, you should get output from the chewie container now.

Thanks for the contribution! Feel free to add yourself to the AUTHORS file

**Pull request merged**
